export default {
    user: {},
    loading: false,
    day: null,
    time: null,
    pickUp: {},
    drop: {},
    shipping: {},
    order: {},
    paymentMethod: {},
    commandList: [],
    distance: '',
    currentDrive: {},
    currentDriveShipping: {},
    driverAtPickLoc: false,
    time: '',
    price: '',
    payNow: false,
    payComplete: false,
    isLocationComplete: false,
    isReservation: null,
    reservationDay: null,
    reservationTime: null,
    currency: 'EUR', 
    error: '',
}